### ISSUE TITLE
First Meetup

### ISSUE THREAD

**Issue by ml242** [beerjs/montreal#1]
I'm going to plan on a date around 4/11, open for venues, sponsors, attendees more than myself, world domination / profit. Or, just talking about javascript.

Any ideas?

**Comment by fxlemire** [comment]
BeerJS, love it!

Never heard of it before. Is there some sort of formula, or it's usually a bunch of folks going out for a beer and fish n' scripts? (i'll work on it)

What I'd suggest not to lose the hype, (if there's any at all), is to set a date to at least brainstorm about an eventual event. Say Wednesday the 20th?

**Comment by ml242** [comment]
@fxlemire 4/20 it is.... 7pm.

Brutopia
1219 Rue Crescent, Montréal, QC H3G 2B1, Canada

Do you want to help admin this? :)

**Comment by fxlemire** [comment]
Brutopia is a fine choice!

I wouldn't mind! Will you be at js-montreal tonight? If so, let's meet!
