### ISSUE TITLE
First Meetup time / location announced 4/20/16

### ISSUE THREAD

**Issue by ml242** [beerjs/montreal#2]
Brutopia
1219 Rue Crescent, Montréal, QC H3G 2B1, Canada

7pm

Please leave a comment if you can attend and know the number of people in your party.

Looking forward to it!

**Comment by fxlemire** [comment]
Count me in. 1

**Comment by ml242** [comment]
Looking forward to meeting you, @fxlemire

**Comment by shannonlal** [comment]
Looking forward to it

**Comment by ml242** [comment]
See you there, @shannonlal 👍

**Comment by abrahamian** [comment]
I'll be there!

**Comment by ewalk153** [comment]
Next time, I'll be there - already have plans for tonight. Thanks for the open invite.

**Comment by ml242** [comment]
Looks like we are seated downstairs. I'm in a blue grey button-up, it looks just like my GitHub picture :)

**Comment by shannonlal** [comment]
On my way.
